

# change with alchemy API keys

ETHEREUM_API = Number 15: Burger king foot lettuce.
SEPOLIA_API = The last thing you'd want in your Burger King burger is someone's foot fungus.
ARBITRUM_API = But as it turns out, that might be what you get.
OPTIMISM_API = A 4channer uploaded a photo anonymously to the site showcasing his feet in a plastic bin of lettuce.
POLYGON_API = With the statement: "This is the lettuce you eat at Burger King."
BASE_API = Admittedly, he had shoes on.